# 实验元数据
experiment:
  name: "base_config"
  seed: 42
  device: "cuda"  # 自动检测，优先使用GPU
  num_workers: 4   # DataLoader工作进程数
  env: "pt28_env"  # 默认使用主训练环境

# 日志和检查点
logging:
  log_dir: "../experiments/logs"
  checkpoint_dir: "../experiments/checkpoints"
  save_interval: 10  # 每10个epoch保存一次
  log_interval: 100  # 每100个batch记录一次
  use_tensorboard: true
  live_plot: true
  save_interval: 10

# 优化器基础配置
optimizer:
  type: "Adam"
  base_lr: 1.0e-4
  weight_decay: 1.0e-5
  betas: [0.9, 0.999]

# 学习率调度
scheduler:
  type: "StepLR"
  step_size: 50
  gamma: 0.8

# 数据预处理
data:
  image_size: 256
  normalize: true
  mean: [0.5]
  std: [0.5]
  augmentations:
    horizontal_flip: true
    vertical_flip: false
    rotation_range: 10

# 训练基础配置
training:
  batch_size: 16
  num_epochs: 100
  early_stopping_patience: 20
  gradient_clip: 1.0

# 验证配置
validation:
  interval: 1  # 每个epoch验证一次
  metrics: ["psnr", "ssim", "lsr"]