# 数据集特定配置
dataset:
  name: "BSD68"
  path: "data/basic_gray/BSD68"
  type: "gray"  # 灰度图像
  
  # 数据分割比例
  split:
    train: 0.8
    val: 0.1
    test: 0.1
  
  # 噪声配置 - 对应开题报告3.4.1节
  noise:
    train:
      type: "gaussian"
      sigma: 25
    test:
      type: "mixed"
      components:
        - type: "gaussian"
          sigma: 25
          ratio: 0.5
        - type: "poisson"
          lambda: 30
          ratio: 0.3
        - type: "impulse"
          density: 0.1
          ratio: 0.2

# 调整训练参数
training:
  batch_size: 32  # 灰度图像可以使用更大的batch size

# 评估配置
evaluation:
  metrics: ["psnr", "ssim", "lsr"]
  robustness_tests:
    noise_types: ["gaussian", "poisson", "impulse"]
    noise_ratio: [0.5, 0.3, 0.2]

metadata:
  purpose: "BSD68数据集上的基准测试"
  expected_outcome: "建立性能基线，用于后续比较"